version: '3'
services:
  client: #Define the client service so we can run it in an isolated environment.
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8888:8888" # Map backend container port to host port
      - "5173:5173" # Map frontend container port to host port
    volumes:
       - "/app/node_modules"
       - "./:/app"